# Generated by Django 5.0.1 on 2025-03-05 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
